In [10]:
import numpy as np
import pandas as pd

In [11]:
wd = pd.read_csv('winequalityN.csv')

In [12]:
wd.head(5)

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [13]:
print(f'Number of empty records: {wd.isna().sum().sum()}')

Number of empty records: 38


In [14]:
wd.dropna(inplace=True)

In [15]:
wd_des = wd.describe()

In [16]:
for i in wd_des.columns:
    if wd_des[i]['mean'] != 0 or wd_des[i]['std']!=1 :
        print("Standardization needed")
        break

Standardization needed


In [17]:
x = wd.iloc[:,:-1].values
y = wd.iloc[:,-1].values
y

array([6, 6, 6, ..., 6, 5, 6])

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder' , OneHotEncoder(),[0])] , remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [19]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x = ss.fit_transform(x)

In [20]:
x

array([[-0.5719307 ,  0.5719307 , -0.16778609, ..., -1.35916011,
        -0.5449872 , -1.41892232],
       [-0.5719307 ,  0.5719307 , -0.70715516, ...,  0.50839916,
        -0.27635393, -0.83218392],
       [-0.5719307 ,  0.5719307 ,  0.67979387, ...,  0.25939126,
        -0.61214551, -0.32926528],
       ...,
       [ 1.74846359, -1.74846359, -0.70715516, ...,  1.25542287,
         1.46976231,  0.42511267],
       [ 1.74846359, -1.74846359, -1.01536606, ...,  2.18920251,
         1.20112905, -0.24544551],
       [ 1.74846359, -1.74846359, -0.93831333, ...,  1.06866695,
         0.86533746,  0.42511267]])

In [24]:
ir = pd.read_csv('Iris.csv')

In [25]:
ir.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [26]:
print(f'Number of empty records: {ir.isna().sum().sum()}')

Number of empty records: 0


In [27]:
ir_des = ir.describe()

In [29]:
for i in ir_des.columns:
  if ir_des[i]['mean']!=0 or ir_des[i]['std']!=1 :
    print('standardization needed')
    break

standardization needed


In [30]:
x2 = ir.iloc[:,:-1].values
y2 = ir.iloc[:,-1].values

In [32]:
ss = StandardScaler()
x2 = ss.fit_transform(x2)

In [33]:
x2

array([[-1.72054204e+00, -9.00681170e-01,  1.03205722e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.69744751e+00, -1.14301691e+00, -1.24957601e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.67435299e+00, -1.38535265e+00,  3.37848329e-01,
        -1.39813811e+00, -1.31297673e+00],
       [-1.65125846e+00, -1.50652052e+00,  1.06445364e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.62816394e+00, -1.02184904e+00,  1.26346019e+00,
        -1.34127240e+00, -1.31297673e+00],
       [-1.60506942e+00, -5.37177559e-01,  1.95766909e+00,
        -1.17067529e+00, -1.05003079e+00],
       [-1.58197489e+00, -1.50652052e+00,  8.00654259e-01,
        -1.34127240e+00, -1.18150376e+00],
       [-1.55888037e+00, -1.02184904e+00,  8.00654259e-01,
        -1.28440670e+00, -1.31297673e+00],
       [-1.53578584e+00, -1.74885626e+00, -3.56360566e-01,
        -1.34127240e+00, -1.31297673e+00],
       [-1.51269132e+00, -1.14301691e+00,  1.06445364e-01,
        -1.28440670e+00